= Il buyback dei titoli bancari: un'arma in più contro la paura da bail-in
// master doc creato per utilizzare autonomamente il capitolo sulla valutazione delle azioni bancarie
Luca Erzegovesi <mailto:luca.erzegovesi@unitn.it[@lerzegov]>
:lang: it
:bib-file: Bibliography.bib
:bib-numeric-order: appearance
:bib-style: apa
:bib-no-links:
:imagesdir: images
:stem:
:sectnums:
:toc: left
:toc-title: Sommario
:example-caption: Esempio
:figure-caption: Figura
//non funziona
:toc-levels: 4
//icone per admonition blocks da Font Awesome
:icons: font
//directory
// cd /Users/luca/Dropbox/2016\ Paper\ Atlante
//per generare il html senza bibliografia
//asciidoctor 99_Buyback_subordinati.adoc
//
//per generare il pdf con bibliografia
//asciidoctor -r asciidoctor-bibtex -r asciidoctor-pdf -b pdf 99_Buyback_subordinati.adoc
//per generare il html con bibliografia
//asciidoctor -r asciidoctor-bibtex 99_Buyback_subordinati.adoc


Nelle turbolenze post-Brexit, il Governo italiano è alla ricerca di soluzioni per tutelare la stabilità delle banche senza esporre il risparmio bancario al rischio di _bail-in_.

stem:[x = (y^2)/(1+r)^n]

La direttiva europea BRRD detta un protocollo di cura delle crisi bancarie che prevede, in rapida sequenza, l'emersione delle perdite latenti e la ricostituzione del capitale di Vigilanza al livello richiesto dalle Autorità (la BCE per le banche "significative" e la Banca d'Italia per le altre). Se dopo la rilevazione delle perdite la banca si ritrova con un capitale azzerato, o insufficiente a raggiungere il target posto dai supervisori (_guidance_), scatta il _bail-in_ (in senso lato): il _capital gap_ si copre con la svalutazione o con la conversione in azioni del debito subordinato e di quello non garantito (sono esclusi i depositi fino a 100.000 euro e i _covered bond_), in ordine inverso di _seniority_, con i privilegi e le esenzioni previste dalla BRRD o dalle norme di recepimento. Soltanto dopo questo _burden sharing_ a carico di azionisti e creditori aggredibili per almeno l'8% del totale di bilancio, la banca può ottenere fondi pubblici (in senso lato) dallo Stato, dai sistemi obbligatori di garanzia dei depositi, o dal Fondo di risoluzione istituito dalla BRRD.

Che lo si chiami risanamento (quando la banca conserva un patrimonio, per quanto insufficiente) o risoluzione (quando la banca è insolvente), il percorso è questo. L'alternativa è la liquidazione della banca, con la tutela dei soli depositanti assicurati.

Anche la ricapitalizzazione precauzionale ex articolo 32.4 della BRRD non sfugge al _burden sharing_. Per quella norma, lo Stato può impegnarsi a iniettare capitale in una banca che rischia la bocciatura agli _stress test_ della BCE, per prevenire il crollo delle sue quotazioni di Borsa e altre ripercussioni sistemiche. Tuttavia, se lo fa a condizioni fuori mercato, Bruxelles intercetta l'aiuto pubblico in arrivo e impone la conta delle perdite latenti e il sacrificio preventivo di azionisti e creditori.

Per gli azionisti e gli obbligazionisti "svalutati"  _bail-in_ è sinonimo di _game over_. La parte sana della banca può essere salvata, ma loro sono fuori. Gli obbligazionisti "riconvertiti" in azionisti hanno invece una seconda _chance_, poiché nelle loro mani può finire una quota del controllo della banca. Se la banca è rilanciata con successo, parteciperanno così al valore ricreato del capitale proprio. Se il risanamento fallisce, subiranno la stessa sorte dei creditori svalutati.

Nel caso di apporti di capitale che non fanno scattare il _bail-in_, gli azionisti sono comunque penalizzati dalla diluizione della loro quota di controllo a vantaggio dei nuovi entranti. I creditori di ogni rango sono invece tutelati al 100%.

La BRRD risponde a un disegno razionale. Nella soluzione delle crisi bancarie, i Governi non possono più seguire la terapia antica, fatta di aiuti pubblici e pazienza. I soldi per gli aiuti creano deficit intollerabili per i contribuenti. La pazienza non serve più, perché il modello di business delle banche è in crisi, e servono tempi biblici per smaltire i postumi di un dissesto con margini risicati. Ecco allora che il rischio sistemico viene trasferito ad azionisti, obbligazionisti e grandi depositanti, tutti investitori consapevoli che se lo assumono in cambio di un'equa remunerazione.

Questo è vero in teoria. La realtà è ben diversa, specialmente in Italia.
//raccolta retail

Per evitare il trauma del _bail-in_ occorre chiamare in soccorso un investitore paziente, disposto a scommettere capitali freschi sul risanamento della banca, o ad acquistare NPL a prezzi superiori a quelli pretesi dagli investitori specializzati in _distressed debt_. Se l'aiuto è sufficiente a colmare il _gap_ di capitale, non serve toccare i diritti dei creditori.

Tuttavia, per evitare la trappola degli aiuti di Stato, gli apporti di capitale e le cartolarizzazioni di NPL devono essere configurati come iniziative consortili, a partecipazione volontaria, che perseguono  fini di stabilità sistemica nell'interesse dei loro aderenti. Ha questa natura lo Schema di intervento volontario del Fondo Interbancario di Tutela dei Depositi, utilizzato per Banca Tercas. Funziona in maniera simile il Fondo temporaneo delle banche di credito cooperativo, introdotto dalla recente riforma. Fa parte della famiglia anche il Fondo Atlante, promosso dai maggiori gruppi bancari italiani e dalla Cassa Depositi e Prestiti, che si è fatto carico degli aumenti di capitale delle due popolari venete e che dovrebbe lanciare entro l'estate un'operazione modello di cartolarizzazione di NPL.

Queste iniziative producono due inconvenienti: (a) le perdite evitate agli investitori nelle banche malate si trasferiscono, attraverso il veicolo consortile, alle banche sane, e  diventano irreversibili se il risanamento fallisce; (b) per evitare effetti di contagio che mettano a rischio le banche sane, occorre limitarsi a pochi interventi con un budget limitato.

Da quanto si è appreso, il Governo intende potenziare queste forme di intervento precauzionale con fondi dello Stato o della Cassa Depositi e Prestiti, per affrontare crisi di banche più grandi o più numerose. Non può farlo nell'attuale quadro di regole senza imporre agli investitori la condivisione  delle perdite emergenti. Si vorrebbe pertanto attenuare il principio del _burden sharing_ in sede di applicazione della BRRD. Il Governatore della Banca d'Italia si è espresso più volte a favore di una revisione della direttiva in tal senso, così come ha fatto l'ABI in nome della tutela costituzionale del risparmio.

Ma non è soltanto Bruxelles che si oppone a un'applicazione più lasca delle regole sul _bail-in_. Nel dibattito, sta prendendo forza




Caso MPS


Come uscirne? Sminare il mercato delle obbligazioni a rischio bail-in




== paragrafi miei tagliati
Il Fondo monetario internazionale è tornato a scrivere sulla crisi delle banche italiane con un http://www.imf.org/external/pubs/cat/longres.aspx?sk=44075.0[paper pubblicato ieri], _Cleaning-up Bank Balance Sheets in Italy_. I problemi sono ormai noti a tutti: troppi crediti deteriorati rispetto al patrimonio, margini in contrazione e _business model_ da aggiornare agli _shock_ tecnologici e demografici.

Malattie croniche, che il sistema sopporta dallo scoppio della crisi globale. Dal 2014, gli equilibri sono saltati in alcune banche regionali: prima Tercas, poi le 4 banche oggetto di "risoluzione" a fine novembre 2015 (Banca Marche, Banca Etruria, CariFerrara e CariChieti), le due popolari venete da poco ricapitalizzate dal Fondo Atlante, e una nutrita lista di banche di credito cooperativo e piccole popolari rilevate da consorelle. Sono oggi in attesa di cure le Casse di risparmio di Cesena, Rimini e San Miniato. E, naturalmente, Banca Monte Paschi, la  più sistemica delle osservate speciali.

== MPS
da prospetto IPO 2015 p. 120
https://www.mps.it/investors/investor-relations/piani_industriali_e_aumenti_di_capitale/Aumento%20di%20capitale%202015/Prospetto%20e%20supplementi/Prospetto_informativo.PDF
L’Autorità di Vigilanza, inoltre, ha richiesto di consolidare anche ai fini prudenziali la partecipazione in Patagonia Finance S.A., veicolo che investe in titoli subordinati emessi dalla Banca e che ha emesso delle note (ABS) che sono state sottoscritte da compagnie assicurative e poste a garanzia di polizze unit linked. Tale trattamento non ha avuto effettivi significativi sul Common Equity Tier 1, ma ha comportato una riduzione del Tier 2 pari a circa Euro 100 milioni.


== new biblio 
Advances in Business-Related Scientific Research Conference 2013 in Venice
(ABSRC 2013 Venice)
March 20-22, 2013, Venice, Italy
THE BANKS' SUBORDINATED DEBT PROBLEM IN CONNECTION
WITH BASEL II AND BASEL III
Draško Veselinovič
Gea College
Slovenia
drasko.veselinovic@gea-college.si
http://www.capitalmarketexperts.org/wp-content/uploads/2013/04/Paper-The-Banks-Subordinated-Debt-Problem-In-Connection-With-Basel-II-and-Basel-III-Dra%C5%A1ko-Veselinovi%C4%8D.pdf
stampato


=== Greece
PERPETUAL BONDS / HYBRID PERPETUAL SUBORDINATED BONDS
http://www.markoulakoslaw.gr/en/p/news/aliktoi-ybridikoi-titloi-omologa-meiomenis-diasfalisis
During 2003-2013, many Greek banks issued hybrid perpetual bonds through their subsidiary companies with registered offices in the island of Jersey/States of Jersey, which they distributed horizontally through their branches  to the total of the consumers/prospective investors, regardless of whether the latter were aware of what they were buying or not.

Indeed, it would be quite difficult for the average investor, who is seeking to secure his money, to comprehend that the product the Bank itself was promoting as being issued by the same,  guaranteed by the same and which, moreover, was to be recalled after 5 years when the investor would redeem his money, was actually:

a)perpetual

b) perpetual as it has no maturity date

c) it had been issued by a shell-corporation with registered office in the Island of Jersey with no assets

d)the mentioned guarantee applies, provided that the issuer accepts to pay; in a different case  there is no guarantee

e) the interests may be discontinued if the Bank faces capital problems

f) the recall after 5 years lies in the discretion of the issuer (the shell-corporation with registered office in Jersey) and has no obligation to do so

g) such products holders in the event of liquidation are ranked at the bottom of the creditors list without any privilege

Subsequently, in 2012-2013, many Greek banks made through their subsidiaries buyback offers at 35-40% of their value,  The holders of said securities had no essential choice, as it made no sense keeping them until their maturity, since they did not have maturity.

On behalf of the the holders of said hybrid perpetual bonds, who were deceived concerning the real properties of said bonds, our firm shall institute class actions claiming the amount of the damages suffered (to wit, i) if they accepted the buyback offer we request for the difference between the buyback offer and the money they invested at the bond's purchase, ii) if they did not accept the offer, the entire amount they invested).


*The Greek “Rescue”: Where Did the Money Go?
An Analysis*
https://ineteconomics.org/uploads/papers/WP29-Bortz.pdf
Pablo G. Bortz 1
Working Paper No. 29
November 2015
ABSTRACT
This paper analyses the financial assistance provided to Greece in the first two rescue
packages granted by the Troika (European Union, European Central Bank and IMF). It
looks particularly carefully at claims by Sinn that a third of the public credit granted to
Greece financed its current account deficit, while another third funded capital flight by
Greek nationals, with only the remaining third used to pay creditors. The paper shows
that Sinn inflates the assistance given to Greece by mixing several different concepts in
the total. It also critically reviews the claim that the assistance was used to finance the
current account deficit or capital flight by Greek citizens. Realistic accounting shows
that 54% of the financial assistance provided to Greece was used to repay (foreign)
debt, while another 21% was used to recapitalize Greek banks (some of which were
owned by foreign institutions). Other claims about the rescue package are also analysed
in relation to the treatment of Greek and foreign banking exposure to sovereign debt.


*The Greek Debt Restructuring: An Autopsy*
Jeromin Zettelmeyer 
European Bank for Reconstruction and Development (EBRD)
Christoph Trebesch 
Ludwig Maximilian University of Munich; CESifo (Center for Economic Studies and Ifo Institute)
G. Mitu Gulati 
Duke University School of Law

August 14, 2013

Peterson Institute for International Economics Working Paper No. 13-8 

Abstract:      
The Greek debt restructuring of 2012 stands out in the history of sovereign defaults. It achieved very large debt relief — over 50 percent of 2012 GDP — with minimal financial disruption, using a combination of new legal techniques, exceptionally large cash incentives, and official sector pressure on key creditors. But it did so at a cost. The timing and design of the restructuring left money on the table from the perspective of Greece, created a large risk for European taxpayers, and set precedents — particularly in its very generous treatment of holdout creditors — that are likely to make future debt restructurings in Europe more difficult.





